config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :contacts, only: [:index, :create]
  get 'signup', to: 'users#new'
  get 'search', to: 'posts#search'
  get 'subject_search', to: 'posts#subject_search'
  post '/guest', to: 'guest_sessions#create'
  resources :users, only: [:edit, :show, :create, :update] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  resources :favorites, only: [:create, :destroy]
  resources :posts, only: [:new, :create, :destroy, :update, :edit, :show]  do
    resources :comments, only: [:create, :destroy, :edit, :update]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  mount_uploader :comment_file, ImageUploader
  belongs_to :user
  belongs_to :post
  validates :comment_content, presence: true, length: { maximum: 255 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      flash[:success] = 'コメントを投稿しました。'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = 'コメントの投稿に失敗しました。'
      redirect_back(fallback_location: root_path)
      @error_comment = @comment
    end
  end
  
  def edit
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:post_id])
    comment = current_user.comments.find(params[:id])
    if comment.update(comment_params)
      flash[:success] = 'コメントは正常に更新されました'
      redirect_to post_path(@post)
    else
      flash.now[:danger] = 'コメントは更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    flash[:success] = 'コメントを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  private
  def comment_params
    params.require(:comment).permit(:comment_content, :post_id, :comment_file) 
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<% if @comments.any? %>
<h3 class="text-center mt-5">コメント一覧</h3>
  <% @comments.each do |comment| %>
    <div class="col-10  offset-1 p-2 mt-3 mb-3 border border-primary rounded" id="content-color">
      <div class="row  justify-content-center">
        <div class="col-2 text-center">
          <%= image_tag comment.user.image.url, class: "image" %>
        </div>
        <div class="col-10">
          <div class="text-left">
            <p><%= link_to comment.user.name, user_path(comment.user), class: "text-decoration-none" %></p>
            <p><%= simple_format(h(comment.comment_content)) %></p>
                  
            <% if comment.comment_file_identifier.to_s.include?(".pdf")  %>
              <object data="<%= comment.comment_file.url %>" type="application/pdf" width="280px" height=""></object>
            <% end %>
            <p><a href=<%= comment.comment_file.url %> download> <%= comment.comment_file_identifier %></a></p>
            <div class="row justify-content-end mt-1">
              <span class="col-7 text-muted">  <%= comment.created_at.to_s(:datetime) %></span>
              <% if current_user == comment.user %>
                <div class="col-5 d-inline-block">
                  <%= link_to "削除", post_comment_path(@post, comment), method: :delete, data: { confirm: "コメントを削除しますか?" }, class: 'btn btn-danger btn-sm d-inline-block'%>
                  <%= link_to "編集", edit_post_comment_path(@post, comment) , class: 'btn btn-primary btn-sm btnpd'%>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>
<div class="col-10 offset-1 border border-primary p-2 rounded mt-3" id="content-color">
  <h2>コメント</h2>
  <%= form_with(model: [@post, @comment]) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <%= f.text_area :comment_content, class: 'form-control mt-4 mb-4', required: true %>
    <%= f.file_field :comment_file, class: 'form-control mb-3' %>
    <%= f.hidden_field :file_cache %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <div class="text-center">
      <%= f.submit '投稿', class: 'btn btn-primary w-100' %>
    </div>
  <% end %>
</div>

app/views/comments/edit.html.erb
<div class="text-center">
  <h1>コメント編集画面 </h1>
</div>
<div class="row justify-content-center">
  <div class="col-8 border border-primary p-2 rounded mt-3" id="content-color">
<h2>コメント</h2>
    <%= form_with(model: [@post, @comment]) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <%= f.text_area :comment_content, class: 'form-control p-1 mb-3', required: true %>
      <% if @comment.comment_file.present?  %>
          (中身：<%= @comment.comment_file_identifier %>)
      <% end %>
      <%= f.file_field :comment_file, class: 'form-control mb-3' %>
      <%= f.hidden_field :file_cache %>
      <%= f.hidden_field :post_id, value: @post.id %>
  </div>
    <div class="text-center mt-3">
      <%= f.submit '更新', class: 'btn btn-primary w-50' %>
    </div>
    <div class="text-center">
      <%= link_to "キャンセル",:back, class: "btn btn-secondary w-50 m-3", data: { confirm: "更新せずもとの画面に戻りますか？" } %>
    </div>
  <% end %>
</div>