config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :contacts, only: [:index, :create]
  get 'signup', to: 'users#new'
  get 'search', to: 'posts#search'
  get 'subject_search', to: 'posts#subject_search'
  post '/guest', to: 'guest_sessions#create'
  resources :users, only: [:edit, :show, :create, :update] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  resources :favorites, only: [:create, :destroy]
  resources :posts, only: [:new, :create, :destroy, :update, :edit, :show]  do
    resources :comments, only: [:create, :destroy, :edit, :update]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 4 }, on: :create
  has_secure_password
  
  has_many :posts
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  has_many :comments
  has_many :favorites
  has_many :favoritings, through: :favorites, source: :post
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def feed_posts
    Micropost.where(user_id: self.following_ids + [self.id])
  end
  
   def favorite(like_post)
    self.favorites.find_or_create_by(post_id: like_post.id)
   end
   
   def unfavorite(like_post)
    favorite = self.favorites.find_by(post_id: like_post.id)
    favorite.destroy if favorite
   end
   
   def favoriting?(posts)
    self.favoritings.include?(posts)
   end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :followings, :follower, :like]
  before_action :exist_user?, only:[:show]
  
  def show
    @user = User.find(params[:id])
    @pagy, @posts = pagy(@user.posts.order(id: :desc))
    @favoritings = @user.favoritings
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank?
      params[:user].delete("password")
    end
    if @user.update(user_params)
      flash[:success] = 'プロフィールは正常に更新されました'
      redirect_to root_url
    else
      flash.now[:danger] = 'プロフィールは更新されませんでした'
      render :edit
    end
  end
  
  def followings
    @user = User.find(params[:id])
     @pagy, @followings = pagy(@user.followings)
  end

  def followers
    @user = User.find(params[:id])
    @pagy, @followers = pagy(@user.followers)
  end
  
  def likes
    @user = User.find(params[:id])
    @pagy, @favoritings = pagy(@user.favoritings.includes([:user]))
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :prefecture_id, :school_id, :profile, :group)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% if object.any? %>
  <div>
    <ul class="list-unstyled">
      <% object.each do |follower| %>
        <li>
          <div class="p-sm-2 my-2">
            <div class="row">
              <div class="col-sm-6 offset-sm-3">
                <div class="row justify-content-center">
                  <div class="col-3 border border-primary p-2"  id="content-color">
                    <%= image_tag follower.image.url, class: "image" %>
                  </div>
                  <div class="col-7 border border-primary p-2 rounded" id="content-color">
                    <div class="text-left">
                      <h4><%= link_to follower.name, user_path(follower), class: "text-decoration-none" %></h4>
                      <p>出身地：<%= follower.prefecture_id %></p>
                      <p>校種：<%= follower.school_id %></p>
                      <p><%= follower.profile %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  <div class="pagination">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>
<% else %>
  <p id="nopost">まだいません</p>
<% end %>

app/views/users/_form.html.erb
<div class="bg-secondary p-sm-2 m-3 p-2 rounded">
      <div class="m-3 form">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control w-100 form-height', required: true %>
      </div>
      
      <div class="m-3">
        <%= f.label :prefecture_id, '都道府県' %>
        <%= f.select :prefecture_id, User.prefecture_ids.keys, class: 'form-control form-height', required: true%>
      </div>
      
      <div class="m-3">
        <%= f.label :school_id, '校種' %>
        <%= f.select :school_id, User.school_ids.keys, class: 'form-control form-height', required: true%>
      </div>
      
      <div class="m-3">
        <%= f.label :image, 'アイコン画像' %>
        <%= f.file_field :image, class: 'form-control form-height'%>
      </div>
      
      <div class="m-3">
        <%= f.label :profile, '自己紹介' %>
        <%= f.text_area :profile, class: 'form-control w-100 form-profile-height', required: true %>
      </div>

      <div class="m-3">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control form-height', required: true %>
      </div>

      <div class="m-3">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control form-height'%>
      </div>

      <div class="m-3">
        <%= f.label :password_confirmation, 'パスワード(確認)' %>
        <%= f.password_field :password_confirmation, class: 'form-control form-height'%>
      </div>
    </div>

app/views/users/_userlikebutton.html.erb
<% if current_user.favoriting?(favorite) %>
  <%= form_with(model: current_user.favorites.find_by(post_id: favorite.id),  method: :delete, data: {remote: true} ) do |f| %>
    <%= hidden_field_tag :post_id, favorite.id , id: "post_#{favorite.id}" %>
    <%= f.submit 'お気に入り解除', class: 'btn btn-danger btn-sm' %>
  <% end %>
<% else %>
  <%= form_with(model: current_user.favorites.build, data: {remote: true} ) do |f| %>
    <%= hidden_field_tag :post_id, favorite.id , id: "post_#{favorite.id}" %>
    <%= f.submit 'お気に入り登録', class: 'btn btn-primary btn-sm' %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>プロフィール編集画面 </h1>
</div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <%= render "form", f: f %>
      <div class="text-center">
        <%= f.submit '更新', class: 'btn btn-primary w-75 mb-4' %>
      </div>
    <% end %>
    <div class="text-center">
      <%= link_to "キャンセル",:back, class: "btn btn-secondary w-75 m-4", data: { confirm: "更新せずに終了しますか？" } %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="text-center">
  <h1><%= @user.name %>さんのフォロワー一覧</h1>
</div>
<%= render 'users/follow', object: @followers %>

app/views/users/followings.html.erb
<div class="text-center">
  <h1><%= @user.name %>さんのフォロワ一覧</h1>
</div>
<%= render 'users/follow', object: @followings %>

app/views/users/likes.html.erb
<div class="text-center">
  <h1><%= @user.name %>さんのお気に入り</h1>
</div>
<% if @favoritings.any? %>
  <ul class="list-unstyled mt-2">
    <% @favoritings.each do |favorite| %>
      <li class="col-sm-6 offset-sm-3">
        <div class="border border-primary p-sm-2 mx-2 p-2 rounded  mb-3" id="content-color">
         <div class="row">
            <div class="col-3 p-1 text-center">
              <p><%= link_to favorite.user.name, user_path(favorite.user), class: "text-decoration-none" %></p>
              <%= image_tag favorite.user.image.url, class: "image" %>
            </div>
            <div class="col-9">
              <div class="text-left">
                <h4>
                  【<%= favorite.subject_id %>】<%= link_to(post_path(favorite), class: 'text-decoration-none') do %>
                    <%= favorite.title %>
                　   <% end%>
                </h4>
                <p><%= favorite.content %></p>
                <p><a href=<%= favorite.file.url %> download> <%= favorite.file_identifier %></a></p>
                <p class="text-muted">  投稿日時： <%= favorite.created_at.to_s(:datetime) %></p>
              </div>
              <div class="col-5" id="favorite_<%= favorite.id %>">
                 <%= render 'userlikebutton', { favorite: favorite }%>
              </div>
            </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%== pagy_bootstrap_nav(@pagy) %>
<% else %>
  <p id="nopost">まだお気に入りはありません</p>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録</h1>
</div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <%= render "form", f: f %>
      <div class="text-center">
        <%= f.submit '新規登録', class: 'btn btn-primary w-75 mb-4' %>
      </div>
    <% end %>
    <div class="text-center mb-5">
      <h3>アカウントをお持ちの方は<%= link_to 'こちら', login_path %>から</h3>
    </div>
  </div>
</div>
 

app/views/users/show.html.erb
<div class="text-center">
  <h1><%= @user.name %>さんのプロフィール</h1>
  <%= render 'relationships/follow_button', user: @user %>
</div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <div class="row justify-content-center">
      <div class="col-3 border border-primary p-2"  id="content-color">
          <%= image_tag @user.image.url, class: "image" %>
        </div>
        <div class="col-7 border border-primary p-2 rounded" id="content-color">
        <div class="text-left">
          <p>出身地：<%= @user.prefecture_id %></p>
          <p>校種：<%= @user.school_id %></p>
          <p><%= simple_format(h(@user.profile)) %></p>
        </div>
      </div>
      <div class="text-center">
        <% if current_user == @user %>
          <%= link_to "編集", edit_user_path(@user) , class: 'btn btn-primary w-50 mt-3'%>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="text-center mt-5">
  <h1><%= @user.name %>さんの投稿</h1>
</div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= render 'posts/index', posts: @posts %>
  </div>
</div>
<div class="text-center">
  <h2><%= link_to "一覧画面へ", root_path, class: "btn btn-success mt-3" %></h2>
</div>