config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :contacts, only: [:index, :create]
  get 'signup', to: 'users#new'
  get 'search', to: 'posts#search'
  get 'subject_search', to: 'posts#subject_search'
  post '/guest', to: 'guest_sessions#create'
  resources :users, only: [:edit, :show, :create, :update] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  resources :favorites, only: [:create, :destroy]
  resources :posts, only: [:new, :create, :destroy, :update, :edit, :show]  do
    resources :comments, only: [:create, :destroy, :edit, :update]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :file, FileUploader
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :favoriteds, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 20 }
  validates :file, presence: true
  validates :subject_id, presence: true
 
 
  def self.search(keyword1, keyword2, keyword3, keyword4, keyword )
    if keyword1 == "校種"
     # keyword1 = ["校種", "小学校", "中学校", "高校"]
       keyword1 = Post.schooltypes.keys
    end
    if keyword2 == "学年"
    #  keyword2 = ["学年", "学年共通", "１年", "２年", "３年", "４年", "５年", "６年"]
       keyword2 = Post.grades.keys
    end
    
    if keyword3 == "教科"
    #  keyword3 = ["教科", "国語", "社会", "数学", "理科", "英語", "音楽", "保体", "技家", "美術", "算数", "生活", "家庭", "図画工作"]
       keyword3 = Post.subject_ids.keys
    end
    
    if keyword4 == "教科書"
    #  keyword4 = ["教科書","東京書籍", "三省堂", "教育出版", "光村図書出版", "帝国書院", "山川出版社", "日本文教出版", "自由社", "育鵬社", "清水書院", "大日本図書", "学校図書", "啓林館", "数研出版", "教育芸術社", "開隆堂出版", "大修館書店", "学研教育みらい", "教育図書", "信州教育出版社"]
       keyword4 = Post.schoolbooks.keys
    end
    where(schooltype: keyword1).where(grade: keyword2).where(subject_id: keyword3).where(schoolbook: keyword4).where(["title like? OR content like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :destroy]
  def new
    @post = Post.new
  end
  
  def show
    @post = Post.find(params[:id])
    @pagy,@comments = pagy(@post.comments.includes(:user))
    @comment = current_user.comments.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'メッセージを投稿しました。'
      redirect_to root_url
    else
      @pagy, @posts = pagy(current_user.posts.order(id: :desc))
      flash.now[:danger] = 'メッセージの投稿に失敗しました。'
      render :new
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_to root_url
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      flash[:success] = '投稿は正常に更新されました'
      redirect_to root_url
    else
      flash.now[:danger] = '投稿は更新されませんでした'
      render :edit
    end
  end
  
  def search
    if current_user.group === nil
      @pagy,@posts = pagy(Post.search(params[:schooltype], params[:grade], params[:subject_id], params[:schoolbook], params[:keyword]))
    else
      showid = User.where(group: current_user.group).ids
      @pagy, @posts = pagy(Post.where(user_id: showid).search(params[:schooltype], params[:grade], params[:subject_id], params[:schoolbook], params[:keyword]))
    end
      @keyword = params[:keyword]
      @schooltype = params[:schooltype]
      @grade = params[:grade]
      @subject_id = params[:subject_id]
      @schoolbook = params[:schoolbook]
      render "search"
  end

  private

  def post_params
    params.require(:post).permit(:title, :subject_id, :content, :file, :file_cache, :grade, :schoolbook, :schooltype)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= render 'layouts/error_messages', model: f.object %>
  <div class="bg-secondary m-4 p-3 rounded">
    <div class="m-3 mb-4">
      <%= f.label :title, 'タイトル' %>
      <%= f.text_field :title, class: 'form-control form-height w-100', required: true %>
    </div>
    <div class="row m-3 justify-content-start">
      <div  class="col-2" id="school_type">
        <%= f.select :schooltype, Post.schooltypes.keys , class: 'form-control' %>
      </div>
      
      <div class="col-6" id="school_grade">
  　　  　<%= f.select :grade, Post.grades.keys , class: 'form-control　school_type'%>
　　　</div>
　　　
　　　<div class="col-3 school_subject" id="subject_select">
  　　　　<%= f.select :subject_id, Post.subject_ids.keys , class: 'form-control' %>
　　　</div>
    
    　<div class="col-3 subjectbook" id="subjectbook">
  　　　　<%= f.select :schoolbook, Post.schoolbooks.keys , class: 'form-control'%>
  　　　</div>
    </div>
    <% if @post.schooltype.present? %>
  　   校種：<%= @post.schooltype %>
    <% end %>
    <% if @post.grade.present? %>
    　学年：<%= @post.grade %>
    <% end %>
    <% if @post.subject_id.present? %>
    　教科：<%= @post.subject_id %>
    <% end %>
    <% if @post.schoolbook.present? %>
      <p class="m-3">教科書：<%= @post.schoolbook %></p>
    <% end %>
    <div class="m-3">
      <%= f.label :content, '内容' %>
      <%= f.text_area :content, class: 'form-control', required: true %>
    </div>

    <div class="m-3">
      <%= f.label :file, 'ファイル' %>
      <% if @post.file.present?  %>
        <% if @post.file_identifier.present? %>
          (中身：<%= @post.file_identifier %>)
        <% else %>
          (ファイル有り)
        <% end %>
      <% end %>      
      <%= f.file_field :file, class: 'form-control' %>
      
      <%= f.hidden_field :file_cache %>
      <%= "投稿可能な拡張子(jpg,jpeg,gif,png,docx,xlsx,pptx,txt,pdf)"%>
    </div>
  </div>

app/views/posts/_index.html.erb
<% if posts.any? %>
  <%= render 'posts/postsindex' , {posts: @posts}%>
  <%== pagy_bootstrap_nav(@pagy) %>
<% else %>
  <p id="nopost">まだ投稿はありません</p>
<% end %>

app/views/posts/_posts.html.erb
<div class="search-form m-2">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    詳細検索：<%= f.select :schooltype, Post.schooltypes.keys, value: @schooltype, class: "form-control"%>
    <%= f.select :grade, Post.grades.keys, value: @grade, class: "form-control"%>
    <%= f.select :subject_id, Post.subject_ids.keys, value: @subject_id, class: "form-control"%>
    <%= f.select :schoolbook, Post.schoolbooks.keys, value: @schoolbook, class: "form-control"%>
    <h4>&lt;検索><%= f.text_field :keyword, value: @keyword, class: "form-control mt-3"%>
    <%= f.submit "検索" ,class: "btn btn-primary"%></h4>
　<% end%>
</div>
 <div>
   <%= render 'posts/index', posts: @posts %>
 </div>

app/views/posts/_postsindex.html.erb
<ul class="list-unstyled">
    <% posts.each do |post| %>
      <li>
        <div class="border border-primary p-sm-2 mx-2 p-2 rounded mb-3" id="content-color">
          <div class="row  justify-content-center">
            <div class="col-3 p-1  text-center">
              <p><%= link_to post.user.name, user_path(post.user), class: "text-decoration-none" %></p>
              <%= image_tag post.user.image.url, class: "image" %>
            </div>
            <div class="col-9">
              <div class="text-left">
                <h4>
                  【<%= post.subject_id %>】<%= link_to(post_path(post), class: 'text-decoration-none') do %>
                    <%= post.title %>
                　   <% end%>
                </h4>
                <p><%= post.content %></p>
                <p><a href=<%= post.file.url %> download> <%= post.file_identifier %></a></p>
                <p class="text-muted">  投稿日時： <%= post.created_at.to_s(:datetime) %></p>
              </div>
              <div  class="container">
                <div class="row">
                  <div class="col-7">
                    <% if current_user == post.user %>
                      <%= link_to "削除", post, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm btnpd'%>
                      <%= link_to "編集", edit_post_path(post) , class: 'btn btn-primary btn-sm btnpd'%>
                    <% end %>
                  </div>
                  <div class="col-5" id="post_<%= post.id %>">
                    <%= render 'favorites/likebutton', { post: post }%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>

app/views/posts/_search.html.erb
<div class="row text-left">
  <div class="col-sm-6 offset-sm-3">
    <% if posts.any? %>
      <%= render 'posts/postsindex' , {posts: @posts}%>
      <%== pagy_bootstrap_nav(@pagy) %>
    <% else %>
      <p id="nopost">該当する投稿はありません</p>
    <% end %>
  </div>
</div>
<div class="text-center">
  <h2><%= link_to "一覧画面へ", root_path, class: "btn btn-success mt-3" %></h2>
</div>

app/views/posts/edit.html.erb
<div class="text-center">
  <h1>編集画面 </h1>
</div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @post) do |f| %>
      <%= render "form", f: f %>
      <div class="text-center">
        <%= f.submit '更新', class: 'btn btn-primary w-75' %>
      </div>
    <% end %>
    <div class="text-center">
      <%= link_to "キャンセル",:back, class: "btn btn-secondary w-75 m-4", data: { confirm: "更新せずもとの画面に戻りますか？" } %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="text-center">
  <h1>投稿画面 </h1>
</div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @post) do |f| %>
      <%= render "form", f: f %>
      <div class="text-center">
        <%= f.submit '投稿', class: 'btn btn-primary w-75' %>
      </div>
    <% end %>
    <div class="text-center">
      <%= link_to "キャンセル",:back, class: "btn btn-secondary w-75 m-4", data: { confirm: "投稿せずにもとの画面に戻りますか？" } %>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <div class="search-form m-2">
      <%= form_with url: search_path, method: :get, local: true do |f| %>
    詳細検索：<%= f.select :schooltype, Post.schooltypes.keys, value: @schooltype, selected: @schooltype, class: "form-control"%>
    <%= f.select :grade, Post.grades.keys, value: @grade, selected: @grade , class: "form-control"%>
    <%= f.select :subject_id, Post.subject_ids.keys, value: @subject_id, selected: @subject_id, class: "form-control"%>
    <%= f.select :schoolbook, Post.schoolbooks.keys, value: @schoolbook, selected: @schoolbook, class: "form-control"%>
    <h4>&lt;検索><%= f.text_field :keyword, value: @keyword, class: "form-control mt-3"%>
    <%= f.submit "検索" ,class: "btn btn-primary"%></h4>
　<% end%>
    </div>
  </div>
</div>
<% unless @schooltype == "校種" && @grade == "学年" && @subject_id == "教科" && @schoolbook == "教科書" && @keyword == ""%>
<div class="text-center">
 <h1>検索結果</h1>
</div>
<div class="row col-sm-6 offset-sm-3 justify-content-center">
  <div class="text-center search-font">
    <span>検索内容：</span>
      <% unless @schooltype == "校種"%>
        <%= @schooltype%>
      <% end %>
      <% unless @grade == "学年"%>
        <%= @grade%>
      <% end %>
      <% unless @subject_id == "教科"%>
        <%= @subject_id%>
      <% end %>
      <% unless @schoolbook == "教科書"%>
        <%= @schoolbook%>
      <% end %>
      <% unless @keyword == ""%>
       「<%= @keyword %>」
      <% end %>
    </div>
 </div>
 <% end %>
 <%= render 'posts/search', posts: @posts %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <div class="border border-primary rounded p-2 m-4" id="content-color">
      <div class="row justify-content-center">
        <div class="col-3 p-1 text-center" >
          <p><%= link_to @post.user.name, user_path(@post.user), class: "text-decoration-none" %></p>
          <%= image_tag @post.user.image.url, class: "image" %>
        </div>
        <div class="col-8">
          <div class="text-left">
          <p>
            <% unless @post.schooltype == "校種"%>
              校種：<%= @post.schooltype %>
            <% end %>
            <% unless @post.grade == "学年"%>
            　学年：<%= @post.grade %>
            <% end %>
            <% unless @post.subject_id == "教科"%>
            　教科：<%= @post.subject_id %>
            <% end %>
          </p>
          <p>
            <% unless @post.schoolbook == "教科書"%>
            教科書：<%= @post.schoolbook %>
            <% end %>
          </p>
          <p><a href=<%= @post.file.url %> download> <%= @post.file_identifier %></a></p>
          <% if @post.file_identifier.include?(".pdf")  %>
            <object data="<%= @post.file.url %>" type="application/pdf" width="" height=""></object>
          <% end %>
          <p><%= simple_format(h(@post.content)) %></p>
          <p class="text-muted">  投稿日時： <%= @post.created_at.to_s(:datetime) %></p>
            <div  class="container">
              <div class="row">
                <div class="col-7">
                  <% if current_user == @post.user %>
                    <%= link_to "削除", @post, method: :delete, data: { confirm: "削除しますか?" }, class: 'btn btn-danger btn-sm btnpd'%>
                    <%= link_to "編集", edit_post_path(@post) , class: 'btn btn-primary btn-sm btnpd'%>
                  <% end %>
                </div>
                <div class="col-5" id="post_<%= @post.id %>">
                  <%= render 'favorites/likebutton', { post: @post }%>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= render 'comments/comments', { post: @post }%>
    <div class="text-center">
      <h2><%= link_to "一覧画面へ", root_path, class: "btn btn-success mt-3" %></h2>
    </div>
  </div>
</div>