config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :contacts, only: [:index, :create]
  get 'signup', to: 'users#new'
  get 'search', to: 'posts#search'
  get 'subject_search', to: 'posts#subject_search'
  post '/guest', to: 'guest_sessions#create'
  resources :users, only: [:edit, :show, :create, :update] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  resources :favorites, only: [:create, :destroy]
  resources :posts, only: [:new, :create, :destroy, :update, :edit, :show]  do
    resources :comments, only: [:create, :destroy, :edit, :update]
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0 list-unstyled">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <div class='fixed-top'>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">教材シェア</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if logged_in? %>
          <div class="btn-group">
            <ul class="navbar-nav">
              <li class="ms-3"><%= link_to '投稿', new_post_path, class: 'nav-link' %></li>
              <li class="ms-3"><%= link_to 'お気に入り', likes_user_path(current_user), class: 'nav-link' %></li>
              <li class="ms-3"><%= link_to 'フォロー', followings_user_path(current_user), class: 'nav-link' %></li>
              <li class="ms-3"><%= link_to 'フォロワー', followers_user_path(current_user), class: 'nav-link' %></li>
              <li class="ms-3"><%= link_to 'ログアウト', logout_path, method: :delete,  class: 'nav-link' %></li>
              <li class="ms-3"><%= link_to 'お問い合わせ', contacts_path , class: 'nav-link' %></li>
              <li class="ms-3"><%= link_to current_user.name , user_path(current_user), class: 'nav-link' %></li>
            </ul>
          </div>
        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to "ゲストログイン", guest_path, method: :post, class: 'nav-link' %></li>
            
          </ul>
        <% end %>
      </div>
    </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>教材シェア</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
    </div>
    <%= yield %>
  </body>
</html>